/**
 * CarePlanCard
 *
 * Visual presentation for Doctor Care Plans.
 * Renders structured DO, AVOID, and FOLLOW-UP guidance issued by clinicians.
 */

function formatDisplayDate(dateVal) {
  if (!dateVal) return "Not specified";
  try {
    return new Date(dateVal).toLocaleDateString("en-IN", {
      day: "2-digit",
      month: "short",
      year: "numeric",
    });
  } catch {
    return String(dateVal);
  }
}

const STATUS_BADGES = {
  active: "bg-emerald-100 text-emerald-800 border-emerald-200",
  completed: "bg-blue-100 text-blue-800 border-blue-200",
  superseded: "bg-slate-100 text-slate-600 border-slate-200",
  discontinued: "bg-red-100 text-red-800 border-red-200",
};

export default function CarePlanCard({ plan, isPatientView = true }) {
  if (!plan) return null;

  const doBlock = plan.DO || { diet: plan.dietRecommended || [], activities: plan.activitiesRecommended || [] };
  const avoidBlock = plan.AVOID || { diet: plan.dietRestricted || [], activities: plan.activitiesRestricted || [] };
  const followUpBlock = plan.FOLLOW_UP || {
    followUpDate: plan.followUpDate,
    notes: plan.notes,
    attendingDoctor: plan.doctorName,
    diagnosisContext: plan.diagnosis,
  };

  const statusClass = STATUS_BADGES[plan.status] || STATUS_BADGES.active;

  return (
    <div className="bg-white rounded-3xl border border-slate-200 shadow-sm hover:shadow-md transition overflow-hidden">
      {/* Header */}
      <div className="bg-gradient-to-r from-slate-900 to-indigo-950 p-6 text-white">
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div>
            <div className="flex items-center gap-2">
              <span className="text-xl">📋</span>
              <span className="text-xs font-bold uppercase tracking-wider bg-indigo-500/30 text-indigo-200 px-2.5 py-0.5 rounded-full border border-indigo-400/30">
                Doctor-Issued Clinical Guidance
              </span>
            </div>
            <h3 className="text-xl font-black mt-2 text-white">{plan.diagnosis}</h3>
            <div className="flex flex-wrap items-center gap-3 mt-1.5 text-xs text-indigo-200">
              <span>
                👨‍⚕️ Prescribed by: <strong className="text-white">{plan.doctorName}</strong>
              </span>
              <span>•</span>
              <span>Issued: {formatDisplayDate(plan.createdAt)}</span>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <span className={`text-xs font-bold px-3 py-1 rounded-full border capitalize ${statusClass}`}>
              ● {plan.status || "Active"}
            </span>
          </div>
        </div>

        {/* Clinical Assurance Disclaimer */}
        <div className="mt-4 bg-white/10 rounded-xl px-3.5 py-2 text-[11px] text-indigo-100 flex items-center gap-2">
          <span>🛡️</span>
          <span>
            This guidance is issued directly by your attending clinician. Treatments and clinical directives are
            never generated by autonomous AI.
          </span>
        </div>
      </div>

      {/* Structured Guidance Blocks: DO, AVOID, FOLLOW-UP */}
      <div className="p-6 space-y-6">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
          {/* DO SECTION */}
          <div className="bg-emerald-50/60 border border-emerald-200/80 rounded-2xl p-5 space-y-4">
            <div className="flex items-center justify-between border-b border-emerald-200/60 pb-2.5">
              <div className="flex items-center gap-2">
                <span className="w-7 h-7 rounded-lg bg-emerald-600 text-white flex items-center justify-center font-black text-sm">
                  DO
                </span>
                <div>
                  <h4 className="font-bold text-emerald-950 text-sm">Recommended Actions</h4>
                  <p className="text-[11px] text-emerald-700">Follow these clinical recommendations</p>
                </div>
              </div>
            </div>

            {/* Recommended Diet */}
            <div>
              <div className="text-xs font-bold uppercase tracking-wider text-emerald-900 mb-2 flex items-center gap-1.5">
                <span>🥗</span> Diet &amp; Nutrition
              </div>
              {doBlock.diet && doBlock.diet.length > 0 ? (
                <ul className="space-y-1.5 text-xs text-slate-700">
                  {doBlock.diet.map((item, idx) => (
                    <li key={idx} className="flex items-start gap-2 bg-white/80 p-2 rounded-lg border border-emerald-100">
                      <span className="text-emerald-600 font-bold">✓</span>
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              ) : (
                <p className="text-xs text-slate-400 italic">No specific dietary recommendations.</p>
              )}
            </div>

            {/* Recommended Activities */}
            <div>
              <div className="text-xs font-bold uppercase tracking-wider text-emerald-900 mb-2 flex items-center gap-1.5">
                <span>🏃</span> Activities &amp; Lifestyle
              </div>
              {doBlock.activities && doBlock.activities.length > 0 ? (
                <ul className="space-y-1.5 text-xs text-slate-700">
                  {doBlock.activities.map((item, idx) => (
                    <li key={idx} className="flex items-start gap-2 bg-white/80 p-2 rounded-lg border border-emerald-100">
                      <span className="text-emerald-600 font-bold">✓</span>
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              ) : (
                <p className="text-xs text-slate-400 italic">No specific activity recommendations.</p>
              )}
            </div>
          </div>

          {/* AVOID SECTION */}
          <div className="bg-rose-50/60 border border-rose-200/80 rounded-2xl p-5 space-y-4">
            <div className="flex items-center justify-between border-b border-rose-200/60 pb-2.5">
              <div className="flex items-center gap-2">
                <span className="w-7 h-7 rounded-lg bg-rose-600 text-white flex items-center justify-center font-black text-sm">
                  AVOID
                </span>
                <div>
                  <h4 className="font-bold text-rose-950 text-sm">Restricted Items</h4>
                  <p className="text-[11px] text-rose-700">Avoid these for recovery &amp; safety</p>
                </div>
              </div>
            </div>

            {/* Restricted Diet */}
            <div>
              <div className="text-xs font-bold uppercase tracking-wider text-rose-900 mb-2 flex items-center gap-1.5">
                <span>🚫</span> Dietary Restrictions
              </div>
              {avoidBlock.diet && avoidBlock.diet.length > 0 ? (
                <ul className="space-y-1.5 text-xs text-slate-700">
                  {avoidBlock.diet.map((item, idx) => (
                    <li key={idx} className="flex items-start gap-2 bg-white/80 p-2 rounded-lg border border-rose-100">
                      <span className="text-rose-600 font-bold">✕</span>
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              ) : (
                <p className="text-xs text-slate-400 italic">No specific dietary restrictions.</p>
              )}
            </div>

            {/* Restricted Activities */}
            <div>
              <div className="text-xs font-bold uppercase tracking-wider text-rose-900 mb-2 flex items-center gap-1.5">
                <span>⚠️</span> Restricted Activities
              </div>
              {avoidBlock.activities && avoidBlock.activities.length > 0 ? (
                <ul className="space-y-1.5 text-xs text-slate-700">
                  {avoidBlock.activities.map((item, idx) => (
                    <li key={idx} className="flex items-start gap-2 bg-white/80 p-2 rounded-lg border border-rose-100">
                      <span className="text-rose-600 font-bold">✕</span>
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              ) : (
                <p className="text-xs text-slate-400 italic">No activity restrictions recorded.</p>
              )}
            </div>
          </div>
        </div>

        {/* FOLLOW-UP SECTION */}
        <div className="bg-indigo-50/70 border border-indigo-200 rounded-2xl p-5">
          <div className="flex items-center gap-2 border-b border-indigo-200/60 pb-2.5 mb-3">
            <span className="w-7 h-7 rounded-lg bg-indigo-600 text-white flex items-center justify-center font-black text-sm">
              📅
            </span>
            <div>
              <h4 className="font-bold text-indigo-950 text-sm">FOLLOW-UP &amp; Clinical Notes</h4>
              <p className="text-[11px] text-indigo-700">Planned review date and attending clinician advice</p>
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs mb-3">
            <div className="bg-white p-3 rounded-xl border border-indigo-100">
              <span className="text-slate-500 font-semibold block text-[11px]">Recommended Follow-Up</span>
              <strong className="text-indigo-900 text-sm font-black">
                {formatDisplayDate(followUpBlock.followUpDate)}
              </strong>
            </div>
            <div className="bg-white p-3 rounded-xl border border-indigo-100">
              <span className="text-slate-500 font-semibold block text-[11px]">Attending Clinician</span>
              <strong className="text-slate-900 text-sm">
                {followUpBlock.attendingDoctor || plan.doctorName}
              </strong>
            </div>
            <div className="bg-white p-3 rounded-xl border border-indigo-100">
              <span className="text-slate-500 font-semibold block text-[11px]">Clinical Context</span>
              <span className="text-slate-800 font-medium">
                {followUpBlock.diagnosisContext || plan.diagnosis}
              </span>
            </div>
          </div>

          {followUpBlock.notes && (
            <div className="bg-white p-3.5 rounded-xl border border-indigo-100 text-xs text-slate-700">
              <strong className="text-slate-900">Doctor's Clinical Instructions: </strong>
              {followUpBlock.notes}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
